exclude = ["./tests", "./vendor", "./node_modules"]

[unicode]
check_zero_width = true
check_variation_selectors = true
check_bidi_controls = true
check_invisible_math = true
check_homoglyphs = true

[unicode.allowlist]
files = [""]
chars = [""]
