name: Test Action

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Test the action using the local action.yml in the root directory
      - name: Run ghost linter
        uses: ./
